### ISSUE TITLE
ReactJS support

### ISSUE THREAD

**Issue by rajkumaar23** [susam/texme#14]
How do I use this package in ReactJS, where the content is fetched via an API and loaded as innerHTML later ?

**Comment by appukuttan-shailesh** [comment]
@rajkumaar23 , @susam .... how to includes this in a ReactJS app?
I wish to use it as a library.

I try doing the import like this:
```import texme from "texme";```

and later in the app I do:
```
var input = "**Foo** $$ {a}_{1} {a}_{2} $$";
    var output = texme.render(input);
    console.log(output);
```

But the problem I get is that as soon as I start the app (`npm start`) it now goes to a screen with this:
![image](https://user-images.githubusercontent.com/24866517/120516352-8b70bc80-c3cf-11eb-9a78-882b3f1b96fe.png)

For some reason the "texme" auto initiates and shows the above. My intention is to simply have some markdown/latex content converted to html.

**Comment by susam** [comment]
Hi @appukuttan-shailesh,

I believe you want to skip automatic rendering on load. Please go through the README's section [Skip Automatic Rendering on Load](https://github.com/susam/texme/blob/1.0.0/README.md#skip-automatic-rendering-on-load) and see if it helps you. Essentially you need to define a `window.texme` object with its value set to `{ renderOnLoad: false }` before TeXMe is loaded. As long as you can ensure that, TeXMe will honour this setting and skip automatic rendering.

**Comment by appukuttan-shailesh** [comment]
Oh I see. Is this a prerequisite even when using it as a library?
https://github.com/susam/texme/blob/1.0.0/README.md#use-texme-as-a-library

Thanks for your prompt response.

**Comment by susam** [comment]
It isn't a prerequisite if TeXMe is used as a library in a standalone application, such as one running in Node.js (not within a web browser). However, if TeXMe is running within a web browser it will begin rendering the page automatically. This is so because the primary purpose of TeXMe is to offer us a way to write self-rendering Markdown (GFM) + LaTeX (MathJax) documents with minimal effort. However, other types of usage, such as using TeXMe as a library within web browser, is supported with configuration options.
