### ISSUE TITLE
Cannot process table format

### ISSUE THREAD

**Issue by uplili** [susam/texme#19]
your code is really nice.But I found it can't work with table format well.

**Comment by LiuYinCarl** [comment]
yes, table can't work.

**Comment by susam** [comment]
Tables will be supported in the next release of TeXMe.

**Comment by susam** [comment]
Support for tables has now been added to TeXMe in version 1.0.0.

The support for tables has been added by supporting [GitHub Flavored Markdown (GFM)](https://github.github.com/gfm/). Until version 0.9.0, TeXMe supported only [CommonMark](https://spec.commonmark.org/). Since version 1.0.0, TeXMe now supports GFM. GFM is a superset of CommonMark. GFM adds support for tables, task-list items, strikethrough, autolinks, and tag filter in addition to CommonMark features.

See [changelog](https://github.com/susam/texme/blob/master/CHANGES.md#100-2021-04-25) for more details on the new release.

**Comment by LiuYinCarl** [comment]
Great work. thanks
