### ISSUE TITLE
MathJax render newline error

### ISSUE THREAD

**Issue by LiuYinCarl** [susam/texme#24]
## test code

``` html
<!DOCTYPE html><script src="https://cdn.jsdelivr.net/npm/texme@1.0.0"></script><textarea>

  # Error test

  $$
  A \rightarrow \beta R \\
  B \rightarrow \alpha R | \epsilon
  $$
```

## rendering effect
![image](https://user-images.githubusercontent.com/29608850/151581736-c6a00407-929b-41dd-9906-29e9ff91b6df.png)

## which rendering effect show be right?
![image](https://user-images.githubusercontent.com/29608850/151582127-d6282fe4-8bd1-4867-80fb-7ef44c7808e3.png)

I think this is a bug of MathJax because I test such code by mathjax.

## test code using MathJax

```html
<!DOCTYPE html>
<head>
<script src="https://cdn.bootcss.com/mathjax/3.0.5/es5/tex-mml-chtml.js"></script>
</head>

<body>
<div>
  $$
  A \rightarrow \beta R \\
  B \rightarrow \alpha R | \epsilon 
  $$
  </div>
  </body>
```

## rendering effect using MathJax
![image](https://user-images.githubusercontent.com/29608850/151584377-0c9f8c9a-fe50-4ff9-9fbf-965307a873f1.png)

Now I have an ugly method to avoid this bug by using two LaTex paragraphs.

```html
<!DOCTYPE html><script src="https://cdn.jsdelivr.net/npm/texme@1.0.0"></script><textarea>

  # Error test

  $$
  A \rightarrow \beta R
  $$
  $$
  B \rightarrow \alpha R | \epsilon
  $$
```

But I think it's not an elegant method. So, Is there any better method to avoid the render question? thanks.

**Comment by LiuYinCarl** [comment]
I found a better way to render multiline equation.

```html
<!DOCTYPE html><script src="https://cdn.jsdelivr.net/npm/texme@1.0.0"></script><textarea>

  # Error test

  $$
  \begin{align}
  & A \rightarrow \beta R \nonumber \\
  & B \rightarrow \alpha R | \epsilon \nonumber
  \end{align}
  $$
```

`&` was used to align two formulas, `\nonumber` was used to avoid the formula number at the end of the line.

## rendering effect
![image](https://user-images.githubusercontent.com/29608850/151590497-620f8465-c865-48a2-8839-9c5d3b1cc179.png)

**Comment by susam** [comment]
The `$$` delimiter is used to typeset a single equation, not multiple equations.

The rendering example you have shown for the first example is correct and expected behaviour. In other words, the LaTeX code `$$ f \\ g $$` renders the text "f" and the text "g" on the same line. This is expected behaviour. The original LaTeX (such as the one available with TeXLive, pdflatex, etc., not MathJax LaTeX) behaves the same way too.

To display multiple equations on separate lines, `align`, `gather`, or some such environment should be used, like you have shown in your second comment. See section 3.2 (Single Equations) and section 3.5 (Multiple Equations) for more details on LaTeX syntax for mathematical typesetting.

**Comment by LiuYinCarl** [comment]
Thank you. I am really a fool.

**Comment by susam** [comment]
You are very welcome. Thank you for using TeXMe. If you have any more questions about it, please do not hesitate to create a new issue for this project on GitHub and ask your questions.
