### ISSUE TITLE
Only rendering TeX content? (ignoring Markdown)

### ISSUE THREAD

**Issue by Pseudomanifold** [susam/texme#26]
Hi! This is an outstanding project and I fell in love with its simplicity!

I was wondering whether it would be possible to support a TeX-only mode, ignoring other Markdown statements altogether? The reason is that I have a bunch of Markdown documents with some maths formulas, but I am already using a Markdown renderer. When I integrate `texme` into the headers of that content, it starts rendering *everything* including some of the meta-tags of the website itself. 

Is there any way around that or is it somewhat opposed to the design intentions of the project?

In any case: thanks a lot for providing such an awesome project!

**Comment by dvd101x** [comment]
Hi, I'm not part of this project

I don't see on the option a way to disable Markdown.

I guess that for TeX only you could use **MathJax** that is what texme use for TeX.

There is also the posibility of using **KaTeX**

**Comment by Pseudomanifold** [comment]
Thanks!

**Comment by susam** [comment]
@Pseudomanifold, I am glad you like TeXMe. Thank you for your comment. The comment by @dvd101x is right. There isn't a way to disable Markdown because it was not something the users of this project (including me) have asked for yet. Usually, when someone is using their own choice of Markdown renderer by themselves, they choose MathJax or KaTeX too by themselves for LaTeX rendering.

**Comment by dvd101x** [comment]
@susam

Btw just wanted to say hi, TeXMe is a great project and I’m very grateful to have access to it. This is fantastic and an inspiration for some projects I’m trying to do.

**Comment by susam** [comment]
Hi @dvd101x! Nice to meet you here and thank you for the kind words about this project. 🙂
