### ISSUE TITLE
Missing /marked/marked.min.js

### ISSUE THREAD

**Issue by Tanavit-M** [susam/texme#30]
I followed the procedure described in "Self-Hosting TeXMe" in order to locally try TexMe.

The file  "/marked/marked.min.js" has been removed from the current "marked" repository.
So, it is notified as missing by  the http server : 
 
127.0.0.1 - - [28/Nov/2023 08:56:18] "GET /marked/marked.min.js HTTP/1.1" 404 -

and your provided "euler.html" example is displaying an empty html page.

I revert my "marked" repository to the 8492faf1ee3acd4118f62a2fae65a34f9210903a commit which make this file to reappear and the html page to correctly display.

May be "euler.html" should be updated according to the new "marked" repository ?

Unfortunately, as I am totally incompetent in both javascript and html, I am unable to suggest a fix.

**Comment by susam** [comment]
Hi @Tanavit-M,

Thank you for the detailed description of the issue.  Indeed the Marked project has removed `marked.min.js` from its source code.  Here is the commit in the Marked project where this file was removed: https://github.com/markedjs/marked/commit/7d95a91093f8b5cbdb30b642d06b0c9dd0ab269d

Since the project maintainers of Marked now want us to download `marked.min.js` directly from the CDN URL, the steps to self-host TeXMe would look like this now:

```sh
git clone https://github.com/susam/texme.git
git clone https://github.com/mathjax/mathjax.git
curl -sSL --create-dirs -o marked/marked.min.js https://cdn.jsdelivr.net/npm/marked/marked.min.js
```

Please let me know if this works for you.  I'll update the README sometime later.

**Comment by Tanavit-M** [comment]
Hello @susam 

Your proposal works perfectly. 

Thanks.
